version: '3.7'

services:
  traefik_main:
    container_name: traefik_main
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_network

networks:
  traefik_network:
    name: traefik_network
    driver: bridge