entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    exposedByDefault: false
    network: traefik_network

accesslog: true

certificatesresolvers:
  httpchallenge_0:
    acme:
      httpchallenge:
        entrypoint: http
      email: ml@brl.ru
      storage: /letsencrypt/acme.json
  tlschallege_0:
    acme:
      tlschallenge: true
      email: ml@brl.ru
      storage: /letsencrypt/acme.json

